import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Movie 411",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
